"""Expand: open the 'tool_surface' retirement span (no data change).

No-op on persisted data. The registry-driven read-tolerance shim does the live work.

Revision ID: 0160
Revises: 0159

Generated by ``bin/aios-retire`` from the registry descriptor — do not hand-edit;
regenerate from the descriptor instead (#1578, epic #1572).
"""

from __future__ import annotations

from collections.abc import Sequence

revision: str = "0160"
down_revision: str | None = "0159"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None



def upgrade() -> None:
    pass


def downgrade() -> None:
    # Forward-only lifecycle. Nothing to reverse.
    pass
