"""Retire: rewrite persisted 'tool_surface' surfaces and guard the contract.

One revision, two phases, one transaction:

1. **Backfill** — EXISTS-pre-checked, set-based rewrite across every surface
   the descriptor declares. High-cardinality surfaces are rewritten in
   bounded ``ctid`` batches to cap lock-hold (the 0066 lesson); insert-only
   tables have their immutability trigger suspended around the rewrite.
   Stamps ``tools_vocab_epoch = 0183`` on each rewritten surface.
2. **Contract abort-guard** — a residue scan over every surface that RAISES
   on any unmigrated row. The raise is in-transaction, so the whole
   migration (backfill included) rolls back and ``alembic_version`` never
   reaches this rev; the boot gate (#1575) holds the line.

``downgrade`` is a no-op (forward-only).

Revision ID: 0183
Revises: 0182

Generated by ``bin/aios-retire`` from the registry descriptor — do not hand-edit;
regenerate from the descriptor instead (#1578, epic #1572).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0183"
down_revision: str | None = "0182"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None



def upgrade() -> None:
    # Order-preserving per-element transform, applied set-based per surface.
    op.execute(r"""
        CREATE FUNCTION _aios_retire_tool_surface_rename_0183(tools jsonb) RETURNS jsonb
        LANGUAGE sql IMMUTABLE AS $fn$
            SELECT coalesce(jsonb_agg(elem ORDER BY ord), '[]'::jsonb)
            FROM (
                SELECT DISTINCT ON (dedup_key) elem, ord
                FROM (
                    SELECT
                        jsonb_set(e, '{type}', to_jsonb(new_type)) AS elem,
                        ord,
                        CASE WHEN new_type IN ('custom', 'mcp_toolset')
                             THEN 'pos:' || ord::text
                             ELSE new_type END AS dedup_key
                    FROM jsonb_array_elements(tools) WITH ORDINALITY AS arr(e, ord)
                    CROSS JOIN LATERAL (
                        SELECT CASE e->>'type'
                            WHEN 'stop_task' THEN 'cancel_call'
                            WHEN 'list_tasks' THEN 'list_calls'
                            ELSE e->>'type'
                        END AS new_type
                    ) mapped
                ) m
                ORDER BY dedup_key, ord
            ) deduped
        $fn$
    """)

    # agents.tools: single EXISTS-guarded set-based UPDATE.
    op.execute("""
        UPDATE agents SET tools = _aios_retire_tool_surface_rename_0183(tools), tools_vocab_epoch = 0183
        WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
    """)

    # agent_versions.tools: high-cardinality → batched to bound
    # lock-hold (the 0066 lesson). Loop until no residue remains.
    op.execute("""
        DO $do$
        DECLARE
            updated integer;
        BEGIN
            LOOP
                UPDATE agent_versions SET tools = _aios_retire_tool_surface_rename_0183(tools), tools_vocab_epoch = 0183
                WHERE ctid IN (
                    SELECT ctid FROM agent_versions
                    WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
                    LIMIT 5000
                );
                GET DIAGNOSTICS updated = ROW_COUNT;
                EXIT WHEN updated = 0;
            END LOOP;
        END
        $do$;
    """)

    # workflows.tools: single EXISTS-guarded set-based UPDATE.
    op.execute("""
        UPDATE workflows SET tools = _aios_retire_tool_surface_rename_0183(tools), tools_vocab_epoch = 0183
        WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
    """)

    # workflow_versions is insert-only at runtime (trigger workflow_versions_no_update); suspend
    # the guard for this migration-owned canonicalisation, as 0154/0155 do.
    op.execute("ALTER TABLE workflow_versions DISABLE TRIGGER workflow_versions_no_update")

    # workflow_versions.tools: single EXISTS-guarded set-based UPDATE.
    op.execute("""
        UPDATE workflow_versions SET tools = _aios_retire_tool_surface_rename_0183(tools), tools_vocab_epoch = 0183
        WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
    """)

    op.execute("ALTER TABLE workflow_versions ENABLE TRIGGER workflow_versions_no_update")

    # wf_runs.tools: high-cardinality → batched to bound
    # lock-hold (the 0066 lesson). Loop until no residue remains.
    op.execute("""
        DO $do$
        DECLARE
            updated integer;
        BEGIN
            LOOP
                UPDATE wf_runs SET tools = _aios_retire_tool_surface_rename_0183(tools), tools_vocab_epoch = 0183
                WHERE ctid IN (
                    SELECT ctid FROM wf_runs
                    WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
                    LIMIT 5000
                );
                GET DIAGNOSTICS updated = ROW_COUNT;
                EXIT WHEN updated = 0;
            END LOOP;
        END
        $do$;
    """)

    # sessions.tools: high-cardinality → batched to bound
    # lock-hold (the 0066 lesson). Loop until no residue remains.
    op.execute("""
        DO $do$
        DECLARE
            updated integer;
        BEGIN
            LOOP
                UPDATE sessions SET tools = _aios_retire_tool_surface_rename_0183(tools), tools_vocab_epoch = 0183
                WHERE ctid IN (
                    SELECT ctid FROM sessions
                    WHERE tools IS NOT NULL AND EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
                    LIMIT 5000
                );
                GET DIAGNOSTICS updated = ROW_COUNT;
                EXIT WHEN updated = 0;
            END LOOP;
        END
        $do$;
    """)

    # connectors.tools_schema: single EXISTS-guarded set-based UPDATE.
    op.execute("""
        UPDATE connectors SET tools_schema = _aios_retire_tool_surface_rename_0183(tools_schema), tools_vocab_epoch = 0183
        WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools_schema) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
    """)

    op.execute("DROP FUNCTION _aios_retire_tool_surface_rename_0183(jsonb)")

    # Belt: abort the whole migration in-transaction if ANY surface still holds a
    # retired token after the backfill above. On abort, every rewrite rolls back
    # and alembic_version never advances to this rev, so the boot gate (#1575) holds.
    op.execute("""
        DO $guard$
        DECLARE
            residue bigint;
        BEGIN
            SELECT sum(c) INTO residue FROM (
        SELECT count(*) FROM agents WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
        UNION ALL
        SELECT count(*) FROM agent_versions WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
        UNION ALL
        SELECT count(*) FROM workflows WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
        UNION ALL
        SELECT count(*) FROM workflow_versions WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
        UNION ALL
        SELECT count(*) FROM wf_runs WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
        UNION ALL
        SELECT count(*) FROM sessions WHERE tools IS NOT NULL AND EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
        UNION ALL
        SELECT count(*) FROM connectors WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools_schema) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
            ) scan(c);
            IF residue IS NOT NULL AND residue > 0 THEN
                RAISE EXCEPTION
                    'retirement contract abort: % unmigrated row(s) remain for tool_surface; '
                    'run the backfill (rev 0183) to convergence before contracting',
                    residue;
            END IF;
        END
        $guard$;
    """)


def downgrade() -> None:
    # Forward-only: canonicalised rows cannot be un-rewritten. Nothing to reverse.
    pass
