"""Backfill: rewrite persisted 'tool_surface' surfaces to canonical.

EXISTS-pre-checked, batched, set-based rewrite across every surface the
descriptor declares. High-cardinality surfaces are rewritten in bounded
``ctid`` batches to cap lock-hold (the 0066 lesson); every statement is
``EXISTS``-guarded so it no-ops on already-fixed rows and is fully
re-runnable. Stamps ``tools_vocab_epoch = 0184`` on each rewritten
surface. ``downgrade`` is a no-op (forward-only).

Revision ID: 0184
Revises: 0183

Generated by ``bin/aios-retire`` from the registry descriptor — do not hand-edit;
regenerate from the descriptor instead (#1578, epic #1572).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0184"
down_revision: str | None = "0183"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None



def upgrade() -> None:
    # Order-preserving per-element transform, applied set-based per surface.
    op.execute(r"""
        CREATE FUNCTION _aios_retire_tool_surface_rename_0184(tools jsonb) RETURNS jsonb
        LANGUAGE sql IMMUTABLE AS $fn$
            SELECT coalesce(jsonb_agg(elem ORDER BY ord), '[]'::jsonb)
            FROM (
                SELECT DISTINCT ON (dedup_key) elem, ord
                FROM (
                    SELECT
                        jsonb_set(e, '{type}', to_jsonb(new_type)) AS elem,
                        ord,
                        CASE WHEN new_type IN ('custom', 'mcp_toolset')
                             THEN 'pos:' || ord::text
                             ELSE new_type END AS dedup_key
                    FROM jsonb_array_elements(tools) WITH ORDINALITY AS arr(e, ord)
                    CROSS JOIN LATERAL (
                        SELECT CASE e->>'type'
                            WHEN 'stop_task' THEN 'cancel_call'
                            WHEN 'list_tasks' THEN 'list_calls'
                            ELSE e->>'type'
                        END AS new_type
                    ) mapped
                ) m
                ORDER BY dedup_key, ord
            ) deduped
        $fn$
    """)

    # agents.tools: single EXISTS-guarded set-based UPDATE.
    op.execute("""
        UPDATE agents SET tools = _aios_retire_tool_surface_rename_0184(tools), tools_vocab_epoch = 0184
        WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
    """)

    # agent_versions.tools: high-cardinality → batched to bound
    # lock-hold (the 0066 lesson). Loop until no residue remains.
    op.execute("""
        DO $do$
        DECLARE
            updated integer;
        BEGIN
            LOOP
                UPDATE agent_versions SET tools = _aios_retire_tool_surface_rename_0184(tools), tools_vocab_epoch = 0184
                WHERE ctid IN (
                    SELECT ctid FROM agent_versions
                    WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
                    LIMIT 5000
                );
                GET DIAGNOSTICS updated = ROW_COUNT;
                EXIT WHEN updated = 0;
            END LOOP;
        END
        $do$;
    """)

    # workflows.tools: single EXISTS-guarded set-based UPDATE.
    op.execute("""
        UPDATE workflows SET tools = _aios_retire_tool_surface_rename_0184(tools), tools_vocab_epoch = 0184
        WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
    """)

    # workflow_versions.tools: single EXISTS-guarded set-based UPDATE.
    op.execute("""
        UPDATE workflow_versions SET tools = _aios_retire_tool_surface_rename_0184(tools), tools_vocab_epoch = 0184
        WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
    """)

    # wf_runs.tools: high-cardinality → batched to bound
    # lock-hold (the 0066 lesson). Loop until no residue remains.
    op.execute("""
        DO $do$
        DECLARE
            updated integer;
        BEGIN
            LOOP
                UPDATE wf_runs SET tools = _aios_retire_tool_surface_rename_0184(tools), tools_vocab_epoch = 0184
                WHERE ctid IN (
                    SELECT ctid FROM wf_runs
                    WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
                    LIMIT 5000
                );
                GET DIAGNOSTICS updated = ROW_COUNT;
                EXIT WHEN updated = 0;
            END LOOP;
        END
        $do$;
    """)

    # sessions.tools: high-cardinality → batched to bound
    # lock-hold (the 0066 lesson). Loop until no residue remains.
    op.execute("""
        DO $do$
        DECLARE
            updated integer;
        BEGIN
            LOOP
                UPDATE sessions SET tools = _aios_retire_tool_surface_rename_0184(tools), tools_vocab_epoch = 0184
                WHERE ctid IN (
                    SELECT ctid FROM sessions
                    WHERE tools IS NOT NULL AND EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
                    LIMIT 5000
                );
                GET DIAGNOSTICS updated = ROW_COUNT;
                EXIT WHEN updated = 0;
            END LOOP;
        END
        $do$;
    """)

    # connectors.tools_schema: single EXISTS-guarded set-based UPDATE.
    op.execute("""
        UPDATE connectors SET tools_schema = _aios_retire_tool_surface_rename_0184(tools_schema), tools_vocab_epoch = 0184
        WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools_schema) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
    """)

    op.execute("DROP FUNCTION _aios_retire_tool_surface_rename_0184(jsonb)")


def downgrade() -> None:
    # Forward-only: canonicalised rows cannot be un-rewritten. Nothing to reverse.
    pass
