"""Contract: guard the 'tool_surface' retirement contract.

Carries the in-transaction **abort-guard**: a residue scan
over every surface that RAISES on any unmigrated row. Because the raise is
in-transaction the migration aborts and ``alembic_version`` never reaches
this contract rev, so the boot gate (#1575) holds the line. The guard is a
belt over the backfill's braces.

Revision ID: 0185
Revises: 0184

Generated by ``bin/aios-retire`` from the registry descriptor — do not hand-edit;
regenerate from the descriptor instead (#1578, epic #1572).
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0185"
down_revision: str | None = "0184"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None



def upgrade() -> None:
    # Belt: abort the whole migration in-transaction if ANY surface still holds a
    # retired token. The backfill (rev N+1) should have left zero residue; a row
    # written between backfill and contract, or missed by a surface bug, MUST
    # abort here rather than silently contract. On abort, alembic_version never
    # advances to this contract rev, so the descriptor-based boot gate (#1575) holds.
    op.execute("""
        DO $guard$
        DECLARE
            residue bigint;
        BEGIN
            SELECT sum(c) INTO residue FROM (
        SELECT count(*) FROM agents WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
        UNION ALL
        SELECT count(*) FROM agent_versions WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
        UNION ALL
        SELECT count(*) FROM workflows WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
        UNION ALL
        SELECT count(*) FROM workflow_versions WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
        UNION ALL
        SELECT count(*) FROM wf_runs WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
        UNION ALL
        SELECT count(*) FROM sessions WHERE tools IS NOT NULL AND EXISTS(SELECT 1 FROM jsonb_array_elements(tools) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
        UNION ALL
        SELECT count(*) FROM connectors WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(tools_schema) e WHERE e->>'type' IN ('stop_task', 'list_tasks'))
            ) scan(c);
            IF residue IS NOT NULL AND residue > 0 THEN
                RAISE EXCEPTION
                    'retirement contract abort: % unmigrated row(s) remain for tool_surface; '
                    'run the backfill (rev 0184) to convergence before contracting',
                    residue;
            END IF;
        END
        $guard$;
    """)



def downgrade() -> None:
    # Forward-only lifecycle. Nothing to reverse.
    pass
