from enum import Enum


class ToolSpecTypeType0(str, Enum):
    ARCHIVE_WORKFLOW = "archive_workflow"
    BASH = "bash"
    CALL_AGENT = "call_agent"
    CALL_SESSION = "call_session"
    CALL_WORKFLOW = "call_workflow"
    CANCEL = "cancel"
    CANCEL_RUN = "cancel_run"
    CREATE_WORKFLOW = "create_workflow"
    EDIT = "edit"
    GET_RUN = "get_run"
    GET_WORKFLOW = "get_workflow"
    GLOB = "glob"
    GREP = "grep"
    HTTP_REQUEST = "http_request"
    LIST_RELATED_SESSIONS = "list_related_sessions"
    LIST_RUNS = "list_runs"
    LIST_RUN_EVENTS = "list_run_events"
    LIST_WORKFLOWS = "list_workflows"
    READ = "read"
    RESUME_GATE = "resume_gate"
    SCHEDULE_WAKE = "schedule_wake"
    SEARCH_EVENTS = "search_events"
    SKILL_ARCHIVE = "skill_archive"
    SKILL_UPSERT = "skill_upsert"
    TRIGGER_CREATE = "trigger_create"
    TRIGGER_LIST = "trigger_list"
    TRIGGER_REMOVE = "trigger_remove"
    TRIGGER_UPDATE = "trigger_update"
    UNARCHIVE_WORKFLOW = "unarchive_workflow"
    UPDATE_WORKFLOW = "update_workflow"
    WAKE_SELF = "wake_self"
    WAKE_SESSION = "wake_session"
    WEB_FETCH = "web_fetch"
    WEB_SEARCH = "web_search"
    WRITE = "write"

    def __str__(self) -> str:
        return str(self.value)
